"use client";

import { Accessibility, Check, Mic, RotateCcw, Volume2, X } from "lucide-react";
import { useState } from "react";
import { usePreferences } from "@/lib/preferencesContext";

export function AccessibilityWidget() {
  const [open, setOpen] = useState(false);
  const [listening, setListening] = useState(false);
  const { t, textScale, setTextScale, highContrast, setHighContrast, colorBlind, setColorBlind, dyslexiaFont, setDyslexiaFont, reduceMotion, setReduceMotion } = usePreferences();

  function readPage() { window.speechSynthesis?.cancel(); window.speechSynthesis?.speak(new SpeechSynthesisUtterance(document.body.innerText)); }
  function startListening() {
    const Recognition = (window as Window & { webkitSpeechRecognition?: new () => { start: () => void; onstart: () => void; onend: () => void; onresult: (event: { results: { [key: number]: { transcript: string }[] } }) => void } }).webkitSpeechRecognition;
    if (!Recognition) { window.alert(t("speechNotSupported")); return; }
    const recognition = new Recognition(); recognition.onstart = () => setListening(true); recognition.onend = () => setListening(false); recognition.onresult = event => { const text = event.results[0][0].transcript; const active = document.activeElement; if (active instanceof HTMLInputElement || active instanceof HTMLTextAreaElement) { const start = active.selectionStart ?? active.value.length; active.setRangeText(text, start, active.selectionEnd ?? start, "end"); active.dispatchEvent(new Event("input", { bubbles: true })); } }; recognition.start();
  }
  const reset = () => { setTextScale(1); setHighContrast(false); setColorBlind(false); setDyslexiaFont(false); setReduceMotion(false); };

  return <div className="fixed bottom-4 right-4 z-50 md:bottom-6 md:right-6"><button type="button" aria-label={t("accessibility")} aria-expanded={open} onClick={() => setOpen(value => !value)} className="flex h-11 w-11 items-center justify-center rounded-full border border-[#8b5cf6]/50 bg-[#11131a] text-[#f7f3ff] shadow-[0_8px_30px_rgba(0,0,0,.35)] transition hover:border-[#a78bfa] hover:text-[#a78bfa] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#55e6ff]"><Accessibility className="h-5 w-5" /></button>{open && <section aria-label={t("accessibility")} className="absolute bottom-14 right-0 w-[min(20.5rem,calc(100vw-2rem))] rounded-md border border-white/[0.1] bg-[#0b0c10] p-3 shadow-2xl"><div className="mb-3 flex items-center justify-between border-b border-white/[0.08] pb-2"><h2 className="font-mono text-[10px] uppercase tracking-widest text-[#f7f3ff]">{t("accessibility")}</h2><button type="button" aria-label={t("close")} onClick={() => setOpen(false)} className="rounded p-1 text-[#a39bb4] hover:text-[#f7f3ff]"><X className="h-3.5 w-3.5" /></button></div><GroupLabel text="READABILITY" /><div className="mb-3 grid grid-cols-3 gap-2"><button type="button" aria-label={t("decreaseText")} onClick={() => setTextScale(.9)} className="a11y-choice">A−</button><button type="button" aria-label="Default text size" onClick={() => setTextScale(1)} className="a11y-choice">A</button><button type="button" aria-label={t("increaseText")} onClick={() => setTextScale(1.15)} className="a11y-choice">A+</button></div><Toggle label={t("dyslexiaFont")} active={dyslexiaFont} onClick={() => setDyslexiaFont(!dyslexiaFont)} /><GroupLabel text="VOICE" /><div className="space-y-2"><button type="button" onClick={startListening} className="a11y-wide"><Mic className="h-4 w-4" />{listening ? t("listening") : t("speechToText")}</button><button type="button" onClick={readPage} className="a11y-wide"><Volume2 className="h-4 w-4" />{t("textToSpeech")}</button></div><GroupLabel text="VISUAL" /><div className="space-y-2"><Toggle label={t("highContrast")} active={highContrast} onClick={() => setHighContrast(!highContrast)} /><Toggle label={t("colorBlind")} active={colorBlind} onClick={() => setColorBlind(!colorBlind)} /><Toggle label={t("reduceMotion")} active={reduceMotion} onClick={() => setReduceMotion(!reduceMotion)} /></div><button type="button" onClick={reset} className="a11y-wide mt-3"><RotateCcw className="h-3.5 w-3.5" />RESET SETTINGS</button><div className="mt-3 flex h-6 items-center justify-center gap-2 rounded-full border border-[#b8a984]/50 font-mono text-[9px] uppercase tracking-wider text-[#8fb69b]"><span className="h-2 w-2 rounded-full bg-[#4d9a6d]" />READY</div></section>}</div>;
}
function GroupLabel({ text }: { text: string }) { return <div className="mb-2 mt-3 font-mono text-[10px] uppercase tracking-[.16em] text-[#a39bb4]">{text}</div>; }
function Toggle({ label, active, onClick }: { label: string; active: boolean; onClick: () => void }) { return <button type="button" aria-pressed={active} onClick={onClick} className="a11y-toggle"><span>{label}</span><span className="a11y-state">{active ? <Check className="h-3.5 w-3.5" /> : "OFF"}</span></button>; }
